---
name: druid-exporter

image:
  name: quay.io/opstree/druid-exporter
  tag: v0.11
  pullPolicy: IfNotPresent

imagePullSecrets: []

annotations: {}

podAnnotations: {}

druidURL: http://druid.opstreelabs.in
logLevel: info
logFormat: json

exporterPort: 8080

## Number of replicasets to retain ##
## default value is 10, 0 will not retain any replicasets and make rollbacks impossible ##
revisionHistoryLimit: 10

serviceAccount:
  create: true

serviceType: ClusterIP

serviceMonitor:
  enabled: false
  namespace: monitoring
  interval: 30s
  scrapeTimeout: 10s
  additionalLabels: {}
  targetLabels: []

securityContext: {}

containerSecurityContext: {}

nodeSelector: {}

tolerations: []

affinity: {}
